const productos = [
	{
		id: "1",
		nombre: "Remera",
		marca: "Montagne",
		imagen: "../images/kf4.jpg",
		precio: 50,
		descripcion: "Remera montagne ideal para montaña",
	},
	{
		id: "2",
		nombre: "Campera",
		marca: "Adidas",
		imagen: "../images/kf1.jpg",
		precio: 100,
		descripcion: "Campera hombre ideal para tus entrenamientos al aire libre",
	},
	{
		id: "3",
		nombre: "Campera",
		marca: "Adidas",
		imagen: "../images/kf3.jpg",
		precio: 150,
		descripcion: "Campera mujer ideal para tus entrenamientos al aire libre",
	},
	{
		id: "4",
		nombre: "Calza",
		marca: "Nike",
		imagen: "../images/kf2.jpg",
		precio: 120,
		descripcion: "Calza deportiva con ajuste en cintura",
	},
	{
		id: "5",
		nombre: "Zapatilla",
		marca: "Hoka",
		imagen: "../images/Zapa Hoka.jpg",
		precio: 250,
		descripcion: "Zapatillas de suela ideal para tus entrenamientos de Montaña",
	},
	{
		id: "6",
		nombre: "Remera",
		marca: "Montagne",
		imagen: "../images/kf5.jpg",
		precio: 70,
		descripcion: "Remera de hombre deportiva. ",
	},
];
